blog_blog:
    resource: "@BlogBlogBundle/Resources/config/routing.yml"
    prefix:   /

blog_account_bundle:
    resource: "@BlogAccountBundle/Resources/config/routing.yml"

blog_admin_bundle:
    resource: "@BlogAdminBundle/Resources/config/routing.yml"

login_check:
    path: /admin/login_check

logout:
    path: /admin/logout