security:
    encoders:
        Blog\AccountBundle\Entity\Account:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: BlogAccountBundle:Account, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern: ^/login$
            anonymous: ~

        secured_area:
            pattern:   ^/admin/
            form_login:
                login_path: blog_admin.security.login
                check_path: login_check
            logout:
                path:   /admin/logout
                target: /

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
